language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor
  - flutter --version
script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib/ test/
  - flutter test --no-pub test/
cache:
  directories:
    - $HOME/.pub-cache

notifications:
  email: false
  slack:
    rooms:
      - secure: "adKLIAZPaNhHkyah22BTfm6iXkgdaQZR4AhdTEPLmGPqaZMNdnLpGOBWtjtRSoyPpZiLCb7hU4ENH8LEBpWogpPBsiYMaQ6XalwqvHL1GqBKwihbgSPFfn3Esj4/1rE/VOl0xEeGzOhjSPk6RJs2ZrMBZsUFpxZNLf8RQvUYKRoX4h0rPQli87G+cpsQx4hv5l6p9NfvN+VA7OJ/oCRAmuGtaZkW6S0ijS3xBH0gLn6zt0vRz+r9TJM/gPqKrpTxUB47X5qAasgSlEzf5C2E4jX4wInMIiVbW/HOfVCN1gDpNwKE3nhqck9stDkOzyHUa6BLIrVygEKgRu2h6larZ9gxzJ4HJbrrXsN0vjLHHRGjql4IUDdv8J6LiApdjsPtvgXfZeX6W+lINLgEKWCtRV7f1qDmcnQkAk1mBg7iWHn06PX5FarQMbcT4aCeTrGiQorAjG6M/LAU5J+h2Tc1EcWQW4+yqMzPAKw0yaxd+4TcjoIJUBPIJRZtokx/68CTJT6FJzkiKhpSRE6eKndegCU0837gOQxXu1CJqxA+5NhQjQhPGAODZHu1ByYTCH1zvpXdsBfopHNh2S8XvblgZw/LZCY+xwCcI4/IGS7OJ1gC0/kgm3rLIRYL+12pWOjYBcxklXQGCymhNS22CpjJDUSEFrQxKyvdbymM86B57IQ="
    on_success: always
    on_failure: always